server:
  port: 3333
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: caas-api
  security:
    username: admin
    password: PaaS-TA

management:
  security:
    enabled: false

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

commonApi:
  url: http://localhost:3334
  authorization:
    id: admin
    password: PaaS-TA

project:
  name: caas-api
  artifactId: caas-api
  description: caas-api management service

caasMaster:
  api:
    url: [master_api_url]:8443
    list:
      services:
        list: "/api/v1/namespaces/{namespace}/services"
        get: "/api/v1/namespaces/{namespace}/services/{name}"
        create: "/api/v1/namespaces/{namespace}/services"
        delete: "/api/v1/namespaces/{namespace}/services/{name}"
      endpoints:
        list: "/api/v1/namespaces/{namespace}/endpoints"
        get: "/api/v1/namespaces/{namespace}/endpoints/{name}"
      pods:
        list: "/api/v1/namespaces/{namespace}/pods"
        get: "/api/v1/namespaces/{namespace}/pods/{name}"
      nodes:
        list: "/api/v1/nodes"
        get: "/api/v1/nodes/{name}"
      replicaSets:
        list: "/apis/apps/v1/namespaces/{namespace}/replicasets"
        get: "/apis/apps/v1/namespaces/{namespace}/replicasets/{name}"
      persistentvolumes:
        list: "/api/v1/persistentvolumes"
        get: "/api/v1/persistentvolumes/{name}"
      persistentVolumeClaims:
        list: "/api/v1/namespaces/{namespace}/persistentvolumeclaims"
        get: "/api/v1/namespaces/{namespace}/persistentvolumeclaims/{name}"
      events:
        list: "/api/v1/namespaces/{namespace}/events"
      roles:
        list: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles"
        get: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles/{name}"
        create: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles"
        delete: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles/{name}"
        update: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/roles/{name}"
      deployments:
        list: "/apis/apps/v1/namespaces/{namespace}/deployments"
        get: "/apis/apps/v1/namespaces/{namespace}/deployments/{name}"
        create: "/apis/apps/v1/namespaces/{namespace}/deployments"
        delete: "/apis/apps/v1/namespaces/{namespace}/deployments/{name}"
      roleBindings:
        list: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings"
        get: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings/{name}"
        create: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings"
        delete: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings/{name}"
        update: "/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}/rolebindings/{name}"
      users:
        get: "/api/v1/namespaces/{namespace}/serviceaccounts/{name}"
        create: "/api/v1/namespaces/{namespace}/serviceaccounts"
        delete: "/api/v1/namespaces/{namespace}/serviceaccounts/{name}"
      namespaces:
        get: "/api/v1/namespaces/{namespace}"
        create: "/api/v1/namespaces"
      resourceQuotas:
        list: "/api/v1/namespaces/{namespace}/resourcequotas"
      secrets:
        get: "/api/v1/namespaces/{namespace}/secrets/{name}"
        create: "/api/v1/namespaces/{namespace}/secrets"